// packages/color-picker/color-picker.tsx
// import React, { useState, useRef, useMemo } from 'react';
// import classNames from 'classnames';
// import './index.scss';
// import useDefault from '../hooks/useDefault';
// import Popup from '../popup';
// import ColorPanel from './color-panel.vue';
// import { ColorPickerProps } from './type';

// export const defaultColor = [
//   {
//     value: 'rgb(206, 55, 46)'
//   },
//   {
//     value: 'rgb(237, 149, 160)'
//   },
//   {
//     value: 'rgb(252, 238, 239)'
//   },
//   {
//     value: 'rgb(232, 109, 44)'
//   },
//   {
//     value: 'rgb(245, 192, 66)'
//   },
//   {
//     value: 'rgb(238, 209, 103)'
//   },
//   {
//     value: 'rgb(127, 225, 89)'
//   },
//   {
//     value: 'rgb(114, 212, 183)'
//   },
//   {
//     value: 'rgb(135, 214, 230)'
//   },
//   {
//     value: 'rgb(216, 238, 242)'
//   },
//   {
//     value: 'rgb(86, 116, 245)'
//   },
//   {
//     value: 'rgb(103, 98, 192)'
//   },
//   {
//     value: 'rgb(223, 221, 252)'
//   },
//   {
//     value: 'rgb(92, 192, 131)'
//   },
//   {
//     value: 'rgb(210, 90, 182)'
//   },
// ]

// const ColorPicker: React.FC<ColorPickerProps> & { Panel: React.ElementType } = (props) => {
//   const {
//     className,
//     style,
//     triggerClassName,
//     triggerStyle,
//     size,
//     value,
//     defaultValue = '#5e62ea',
//     colorList = defaultColor,
//     onChange,
//     onTrigger,
//     ...restProps
//   } = props

//   const [innerValue, setInnerValue] = useDefault(value, defaultValue, onChange);
//   const [visible, setVisible] = useState(false)

//   const currentColor = useRef(innerValue)
//   const handleChange = (val: string) => {
//     setInnerValue(val)
//     currentColor.current = val
//   }

//   const popupChange = (val: boolean) => {
//     if (val) {
//       document.documentElement.style.overflowY = 'hidden';
//     } else {
//       document.documentElement.style.overflowY = '';
//     }
//     setVisible(val)
//     onTrigger?.(currentColor.current, val)
//   }

//   const handleClose = () => {
//     setVisible(false)
//     onTrigger?.(currentColor.current, false)
//   }

//   const colorPanel = useMemo(() =>
//     <ColorPanel
//       value={innerValue}
//       colorList={colorList}
//       onChange={handleChange}
//       onClose={handleClose}
//     />, [visible]
//   )

//   return (
//     <div
//       className={classNames(
//         'i-color-picker',
//         className
//       )}
//       style={{ ...style }}
//       {...restProps}
//     >
//       <Popup
//         visible={visible}
//         content={colorPanel}
//         trigger="click"
//         placement='bottom-left'
//         onTrigger={popupChange}
//       >
//         <div
//           className={classNames(
//             'i-color',
//             size && `i-color--size-${size}`,
//             triggerClassName
//           )}
//           style={{ ...triggerStyle, background: innerValue }}
//         ></div>
//       </Popup>
//     </div>
//   )
// }

// ColorPicker.Panel = ColorPanel;

// ColorPanel.displayName = 'ColorPanel';
// ColorPicker.displayName = 'ColorPicker';

// export default ColorPicker;

// packages/color-picker/color-picker.vue
<template>
  <div class="i-color-picker">
    <Popup
      :visible="visible"
      :disabled="disabled"
      trigger="click"
      placement="bottom-start"
      noPadding
      @trigger="popupChange"
    >
      <div
        :class="[
          'i-color',
          disabled && 'i-color__disabled',
          size && `i-color--size-${size}`,
          triggerClassName
        ]"
        :style="{ ...triggerStyle, background: innerValue }"
      ></div>
      <template #content>
        <ColorPanel
          :value="innerValue"
          :colorList="colorList"
          @change="handleChange"
          @close="handleClose"
        />
      </template>
    </Popup>
  </div>
</template>

<script setup lang="ts">
import { computed, CSSProperties, ref } from 'vue'
import { Popup } from '../Popup'
import ColorPanel from './color-panel.vue'
import { colorListType, defaultColor } from './type'

interface ColorPickerProps {
  /**
   * 触发颜色块类名
   */
  triggerClassName?: string
  /**
   * 触发颜色块样式
   */
  triggerStyle?: CSSProperties
  /**
   * 触发颜色块尺寸
   * @default medium
   */
  size?: 'small' | 'medium' | 'large'
  /**
   * 固定颜色值（受控）
   */
  value?: string
  /**
   * 默认颜色值（非受控）
   * @default #5e62ea
   */
  defaultValue?: string
  /**
   * 底部预设颜色
   */
  colorList?: colorListType[]
  /**
   * 是否禁用颜色选择器
   * @default false
   */
  disabled?: boolean
}

interface ColorPickerEmits {
  /**
   * 修改颜色值时触发
   */
  (type: 'change', val: string): void
  /**
   * 切换颜色面板时触发
   */
  (type: 'trigger', val: string, visible: boolean): void
}

const {
  triggerClassName,
  triggerStyle,
  size,
  value,
  defaultValue = '#5e62ea',
  colorList = defaultColor,
  disabled = false
} = defineProps<ColorPickerProps>()
const emit = defineEmits<ColorPickerEmits>()

const _colorPickerValue = ref(defaultValue)
const innerValue = computed(() => value ?? _colorPickerValue.value)

const visible = ref(false)

const currentColor = ref<string>(innerValue.value)
const handleChange = (val: string) => {
  if (currentColor.value !== val) {
    _colorPickerValue.value = val
    emit('change', val)
    currentColor.value = val
  }
}

const popupChange = (val: boolean) => {
  visible.value = val
  emit('trigger', currentColor.value, val)
}

const handleClose = () => {
  visible.value = false
  emit('trigger', currentColor.value, false)
}
</script>

<style lang="scss">
@import './index.scss';
</style>
